services/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from .views import callback_form_view, callback_complete_view  


urlpatterns = [
    path('', views.login, name='login'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('check_profile_completion/', views.check_profile_completion, name='check_profile_completion'),
    path('check_user_exists/', views.check_user_exists, name='check_user_exists'),
    path('services/', views.service_list, name='service_list'),
    path('services/add/', views.service_create, name='service_create'),
    path('services/<int:pk>/edit/', views.service_update, name='service_update'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('services/<int:service_id>/rates/', views.service_rate_list, name='service_rate_list'),
    path('services/<int:service_id>/rates/add/', views.service_rate_create, name='service_rate_create'),
    path('services/<int:service_id>/rates/<int:pk>/edit/', views.service_rate_update, name='service_rate_update'),
    path('services/<int:service_id>/rates/<int:pk>/delete/', views.service_rate_delete, name='service_rate_delete'),
    path('calculate-amount/', views.calculate_amount, name='calculate_amount'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('save_cart_data/', views.save_cart_data, name='save_cart_data'),
    path('user_dashboard/', login_required(views.user_dashboard), name='user_dashboard'),
    path('calculate-amount/user_dashboard/', login_required(views.user_dashboard), name='calculate-amount/user_dashboard'),
    path('logout/', views.logout, name='logout'),
    path("payment/", views.generate_order, name="generate_order"),
    path("topuppayment/", views.generate_topup_order, name="generate_topup_order"),
    path("home/", views.home, name="home"),
    path("quality/", views.quality, name="quality"),
    path("payment/update-status/", views.update_payment_status, name='update_payment_status'),
    path('download-invoice/', views.download_invoice, name='download_invoice'),
    path('coordinator_dashboard/', views.coordinator_dashboard, name='coordinator_dashboard'),
    path('update_casecount/<int:cart_item_id>/', views.update_casecount, name='update_casecount'),
    path('upload_file/<int:profileId>/', views.upload_file, name='upload_file'),
    path('download_latest_file/<int:user_id>/', views.download_latest_file, name='download_latest_file'),
    path('user/details/', views.get_user_details, name='get_user_details'),
    path('get_user_files/<int:user_id>/', views.get_user_files, name='get_user_files'),
    path('download_all_files_as_zip/<int:user_id>/', views.download_all_files_as_zip, name='download_all_files_as_zip'),
    path('get_user_orders/<int:user_id>/', views.get_user_orders, name='get_user_orders'),
    path('download_single_invoice/<int:user_id>/<str:provider_order_id>/', views.download_single_invoice, name='download_single_invoice'),

    ################################### Multiform URL's ########################################
    #------------------------------------ Himanshu --------------------------------------------#
    path('radiologist', views.index, name='index'), 
    path('work', views.work, name='work'), 
    path('coordinator', views.coordinator, name = 'coordinator'),
    path('step1/', views.step1, name='step1'),
    path('step2/', views.step2, name='step2'),
    path('step3/', views.step3, name='step3'),
    path('step4/', views.step4, name='step4'),
    path('step5/', views.step5, name='step5'),
    path('step6/', views.step6, name='step6'),
    path('step7/', views.step7, name='step7'),
    path('submit/', views.submit, name='submit'),
    path('registration_pending/<int:pk>/', views.registration_pending, name='registration_pending'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('coordinator/', views.multiform_coordinator_dashboard, name='coordinator'),
    path('supercoordinator/', views.supercoordinator_dashboard, name='supercoordinator_dashboard'),
    # path('update_status/<int:pk>/', views.update_status, name='update_status'),
    path('update_stage1status/<int:pk>/', views.update_stage1status, name='update_stage1status'),
    path('update_stage2status/<int:pk>/', views.update_stage2status, name='update_stage2status'),
    # the below url is for handling the logic of the callback form page.
    path('callback-form/', callback_form_view, name='callback_form'),
    path('callback-complete/', callback_complete_view, name='callback_complete'),
    path('view_complete_form/<int:pk>/', views.view_complete_form, name='view_complete_form'),
    path('update_messages/', views.update_messages, name='update_messages'),
    # The below url is for getting the response in pdf format.
    path('generate_pdf/<int:pk>/', views.generate_pdf, name='generate_pdf'),
    # This is the url to go to the success page after submitting the form.
    path('success/<int:pk>/', views.success, name='success'),
    # This is the url to see the response page after form submission.
    path('view_response/<int:pk>/', views.view_response, name='view_response'),
    # This is the url to go to the ratelist page.
    path('rate_list/<int:radiologist_id>/', views.rate_list, name='rate_list'),
    
    # This is the url to update the ratelist status.
    path('update_status_rate_list/', views.update_status_rate_list, name='update_status_rate_list'),
    path('check_email_existence/', views.check_email_existence, name='check_email_existence'),
    # To get the callback form modal on the coordinator's page.
    path('view_callback_form/<int:pk>/', views.view_callback_form, name='view_callback_form'),
    # Here are the urls to get the ratelist status and update form on the coordinator's page .
    path('view_rate_list_form/<int:radiologist_id>/', views.view_rate_list_form, name='view_rate_list_form'),
    path('update_rate_list/<int:radiologist_id>/', views.update_rate_list, name='update_rate_list'),
    # the url to send the confirmation email from the coordinator's page.
    path('send_confirmation_mail/<int:user_id>/', views.send_confirmation_mail, name='send_confirmation_mail'),

    #################################### End of Multiform URL's #####################################
    path('apply-promo-code', views.apply_promo_code, name='apply_promo_code'),   # for Promo-Code
    path('download-invoice/<int:order_id>/', views.download_invoice, name='download_invoice'), # for single invoice
    path("generate_order/", views.generate_cart_order, name="generate_cart_order"),
]

u4rad_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from services.views import home_redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models/CallbackForm.py
from django.db import models
from .personal_info import PersonalInformation

class Callback(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    qualification = models.CharField(max_length=100, null=True, default=None, blank=True)
    experience = models.PositiveIntegerField(null=True, default=None, blank=True)
    ctcheckbox = models.BooleanField(default=False)
    mricheckbox = models.BooleanField(default=False)
    xraycheckbox = models.BooleanField(default=False)
    mammographycheckbox = models.BooleanField(default=False)
    # personal_information = models.ForeignKey(PersonalInformation, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.name

services/models/CartItem.py
from django.db import models
from .models import Service
from django.contrib.auth.models import User

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, default=1)
    quantity = models.PositiveIntegerField(default=0)
    casecount = models.PositiveIntegerField(default=0)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    def __str__(self):
        return f"Cart Item: {self.service.service_name} (Quantity: {self.quantity})"

services/models/CartValue.py
from django.db import models
from django.contrib.auth.models import User

class CartValue(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    promo_code = models.CharField(max_length=100, blank=True, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart Item: {self.user} (Created at: {self.created_at})"

services/models/OTP.py
from django.db import models
from django.contrib.auth.models import User

class OTP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)

services/models/Order.py
from django.db import models
from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _
from .constants import PaymentStatus
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    name = CharField(_("Customer Name"), max_length=254, blank=False, null=False)
    amount = models.FloatField(_("Amount"), null=False, blank=False)
    status = CharField(_("Payment Status"),default=PaymentStatus.PENDING, max_length=254, blank=False, null=False,)
    provider_order_id = models.CharField(_("Order ID"), max_length=40, null=False, blank=False)
    payment_id = models.CharField(_("Payment ID"), max_length=36, null=False, blank=False)
    signature_id = models.CharField(_("Signature ID"), max_length=128, null=False, blank=False)
    order_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.id}-{self.name}-{self.status} on {self.order_date}"

services/models/OrderHistory.py
from django.db import models
from django.contrib.auth.models import User

class OrderHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=255)
    quantity = models.IntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order by {self.user} for {self.service_name} on {self.order_date}"

services/models/PromoCode.py
from django.db import models
from django.utils import timezone

class PromoCode(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    active = models.BooleanField(default=True)

    def is_valid(self):
        now = timezone.now()
        return self.active and self.valid_from <= now <= self.valid_to

    def __str__(self):
        return self.code

services/models/Transaction.py
# transaction.py

from django.db import models
from django.contrib.auth.models import User
from .models import Service  # Adjust the import based on your app structure

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    promo_code = models.CharField(max_length=50, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=50)
    provider_order_id = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100)
    signature_id = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transaction {self.provider_order_id} by {self.user.username}"

services/models/constants.py
class PaymentStatus:
    SUCCESS = "Success"
    FAILURE = "Failure"
    PENDING = "Pending"

services/models/personal_info.py
from django.db import models

class PersonalInformation(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=15, null=True, default=None, blank=True)
    cnfpassword = models.CharField(max_length=15, null=True, default=None, blank=True)
    address = models.CharField(max_length=200)
    contact_no = models.CharField(max_length=15)
    resume = models.FileField(upload_to='uploads/')
    photo = models.ImageField(upload_to='uploads/')
    experience_years = models.PositiveIntegerField()
    # status = models.CharField(max_length=20, choices=[('under_progress', 'Under Progress'), ('completed', 'Completed')], default='under_progress', null=False)
    stage1status = models.CharField(max_length=23, choices=[('applied', 'Applied'), ('under_progress', 'Under Progress'), ('verified_by_coordinator', 'Verified by Coordinator'), ('verification_failed', 'Verification Failed')], default='applied')
    stage2status = models.CharField(max_length=28, choices=[('applied', 'Applied'), ('under_progress', 'Under Progress'), ('verified_by_supercoordinator', 'Verified by Supercoordinator'), ('verification_failed', 'Verification Failed')], default='applied')
    coordinator_message = models.CharField(max_length=100, null=True, blank=True)
    supercoordinator_message = models.CharField(max_length=100, null=True, blank=True)
    email_sent = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

services/models/profile.py
# models.py

from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=100, blank=True)
    organization = models.CharField(max_length=100, blank=True)

class UploadFile(models.Model):
    profile = models.ForeignKey(Profile, related_name='uploads', on_delete=models.CASCADE, default=None, null=True, blank=True)
    file = models.FileField(upload_to='uploads/')
    upload_time = models.DateTimeField(auto_now_add=True)

services/forms.py
from django import forms
from .models.models import Service, ServiceRate
from .models.profile import Profile

################ multiform imports ########################
#--------------------Himanshu-----------------------------#
from .models.personal_info import PersonalInformation
from .models.educational_info import EducationalDetails
from .models.workexp_info import ExperienceDetails
from .models.achievement_info import AchievementDetails
from .models.banking_info import BankingDetails
from .models.reportingarea_info import ReportingAreaDetails
from .models.timeavailability_info import AvailabilityDetails
from .models.CallbackForm import Callback

############## End of Multiform imports ###################

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['service_name', 'is_active']

class ServiceRateForm(forms.ModelForm):
    class Meta:
        model = ServiceRate
        fields = ['service', 'min_quantity', 'max_quantity', 'rate']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['email', 'address', 'organization']          


################### Multiform classes ######################
#--------------------- Himanshu ---------------------------#
class CallbackForm(forms.ModelForm):
    class Meta:
        model = Callback
        fields = '__all__'

class PersonalInformationForm(forms.ModelForm):
    class Meta:
        model = PersonalInformation
        fields = '__all__'

class EducationalInfoForm(forms.ModelForm):
    class Meta:
        model = EducationalDetails
        fields = '__all__'

    tenthcertificate = forms.FileField(required=False)
    twelthcertificate = forms.FileField(required=False)
    mbbsmarksheet = forms.FileField(required=False)
    mbbsdegree = forms.FileField(required=False)
    mdmarksheet = forms.FileField(required=False)
    mddegree = forms.FileField(required=False)
    videofile = forms.FileField(required=False)

class WorkExperienceForm(forms.ModelForm):
    class Meta:
        model = ExperienceDetails
        fields = '__all__'

class AchievementsInfoForm(forms.ModelForm):
    class Meta:
        model = AchievementDetails
        fields = '__all__'

class BankingDetailsForm(forms.ModelForm):
    class Meta:
        model = BankingDetails
        fields = '__all__'

####################### End of multiform classes #############################

services/templates/services/callback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Payment complete</h1>
    <form method="post" action="{% url 'callback' %}">
        {% csrf_token %}
        <!-- Other form fields -->
        <button type="submit">Submit</button>
    </form>
</body>
</html>

services/templates/services/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Payment Error</h1>
    <p>{{ error }}</p>
</body>
</html>

services/templates/services/index.html
{% extends 'base_generic.html' %}
{% block content %}
<div class="col-6 mx-auto" style="margin-top:10%;">
    <form action="{% url 'payment' %}" method='POST'>
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Name</label>
          <input type="name" name="name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Amount</label>
          <input type="number" name="amount" class="form-control" id="exampleInputPassword1">
        </div>
        <div>
        <button type="submit" class="btn btn-primary">Pay Now</button>
        </div>
      </form>
</div>
{% endblock %}

services/templates/services/payment.html
{% extends 'base_generic.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options = {
        key: "{{razorpay_key}}",
        amount: "{{order.amount}}", 
        currency: "INR",
        name: "{{order.name}}",
        description: "Test Transaction",
        image: "https://example.com/your_logo",
        order_id: "{{order.provider_order_id}}",
        callback_url: "{{callback_url}}",
        redirect: true,
        prefill: {
            "name": "Gaurav Kumar",
            "email": "gaurav.kumar@example.com",
            "contact": "9999999999"
        },
        notes: {
            "address": "Razorpay Corporate Office"
        },
        theme: {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.open();
    </script>
    <input type="hidden" custom="Hidden Element" name="hidden">
</form>
{% endblock %}

services/templates/services/quality.html
{% extends 'services/base_generic.html' %} {% block content %} {% load static %}
<style>
  /* Ensure the container has some padding */
  .container {
    padding: 0 15px;
  }

  /* Define the grid container */
  .grid-container {
    display: grid;
    grid-template-columns: 1fr;
    gap: 5rem;

  }

  /* Media query for larger screens */
  @media (min-width: 768px) {
    .grid-container {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  

  /* Card adjustments for better spacing */
  .card {
    margin-bottom: 1rem;
  }

  /* Ensure the 'NEXT' button is aligned to the end */
  .textend {
    text-align: center;
  }
</style>
<div class="container my-4 text-center">
  <div class="grid-container">
    <div class="card text-white bg-primary mb-3">
      <div class="card-header">QUALITY</div>
      <div class="card-body">
        <p class="card-text">
          At U4RAD, we always strive for quality, best in the market. We ensure
          that all the imaging protocols are being followed and reporting is
          done by the qualified Radiologists. At U4RAD, we implement quality
          assurance programs to monitor and improve the quality of reporting
          services. Quality reviewing of the cases is followed including
          self-review, peer review, superior review, and review based on
          feedback. Here at U4RAD, we always work to have reporting errors less
          than what is acceptable by National Institute of Health (NIH) and
          American medical association (AMA).
        </p>
      </div>
    </div>
    <div class="card text-white bg-secondary mb-3">
      <div class="card-header">TURNAROUND TIME</div>
      <div class="card-body">
        <p class="card-text">
          We are available 24*7 for reporting of cases. Emergency cases are
          reported within 30 min while regular cases of CT and MRI are reported
          in 3-4 hours. We report Xray and ECG within 1 hour which allows the
          consultant to make a timely decision.
        </p>
      </div>
    </div>
    <!-- <div class="card text-white bg-success mb-3">
      <div class="card-header">REQUIREMENT</div>
      <div class="card-body">
        <p class="card-text">
          • Windows 10 or higher (64-bit). • A minimum of 4GB RAM or more. •
          Minimum 500 GB free disk space. • Computer needs to be connected to
          the internet and connected to same LAN as your modalities. • Ensure
          the computer is up to date. • Hospital/Centre needs to share full
          address and contact details (of Manager/Technician) with email ID.
        </p>
      </div>
    </div> -->
  </div>
  <div class="textend">
    <a class="btn btn-light mt-3 text-center" href="{% url 'calculate_amount' %}"
      >NEXT</a
    >
  </div>
</div>


{% endblock %}

services/templates/services/service_confirm_delete.html
{% extends 'services/base_generic.html' %}

{% block content %}
<style>
  /* Custom styles for delete service confirmation */
  .delete-container {
    max-width: 600px;
    margin: 20px auto;
    padding: 20px;
    background-color: #ffffff;
    border: 1px solid #e9ecef;
    border-radius: 4px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }

  h2 {
    margin-bottom: 20px;
    color: #333;
  }

  p {
    margin-bottom: 20px;
    font-size: 16px;
    color: #555;
  }

  form {
    display: flex;
    justify-content: flex-end;
  }

  button[type="submit"] {
    background-color: #dc3545; /* Red color for delete */
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
  }

  button[type="submit"]:hover {
    background-color: #c82333; /* Darker red on hover */
  }
</style>
<div class="delete-container">
  <h2>Delete Service</h2>
  <p>Are you sure you want to delete "{{ service.service_name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
</div>
{% endblock %}

services/templates/services/service_form.html
{% extends 'services/base_generic.html' %}

{% block content %}
<style>
  /* Custom styles for service form */
  .form-container {
    max-width: 600px;
    margin: 20px auto;
    padding: 20px;
    background-color: #ffffff;
    border: 1px solid #e9ecef;
    border-radius: 4px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }

  h2 {
    margin-bottom: 20px;
    color: #333;
  }

  form {
    display: flex;
    flex-direction: column;
  }

  label {
    font-weight: bold;
    margin-bottom: 8px;
  }

  input[type="text"],
  select {
    padding: 8px;
    margin-bottom: 15px;
    border: 1px solid #ced4da;
    border-radius: 4px;
    font-size: 16px;
    width: calc(100% - 16px); /* Adjust for padding */
  }

  button[type="submit"] {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
    margin-top: 10px;
    align-self: flex-end;
  }

  button[type="submit"]:hover {
    background-color: #0056b3;
  }
</style>


<div class="form-container">
  <h2>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Service</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
</div>
{% endblock %}

services/templates/services/service_rate_confirm_delete.html
{% extends 'services/base_generic.html' %}

{% block content %}
<style>
  /* Custom styles for delete service confirmation */
  .delete-container {
    max-width: 600px;
    margin: 20px auto;
    padding: 20px;
    background-color: #ffffff;
    border: 1px solid #e9ecef;
    border-radius: 4px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }

  h2 {
    margin-bottom: 20px;
    color: #333;
  }

  p {
    margin-bottom: 20px;
    font-size: 16px;
    color: #555;
  }

  form {
    display: flex;
    justify-content: flex-end;
  }

  button[type="submit"] {
    background-color: #dc3545; /* Red color for delete */
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
  }

  button[type="submit"]:hover {
    background-color: #c82333; /* Darker red on hover */
  }
</style>
<div class="delete-container">
  <h2>Delete Rate</h2>
  <p>Are you sure you want to delete rate for {{ rate.min_quantity }} - {{ rate.max_quantity }}?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
</div>
{% endblock %}

services/templates/services/update_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center shadow rounded">
                        <h1 class="text-center mb-4">Update Profile</h1>
                        <form id="update-profile-form" method="post" class="bg-white">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_email" class="form-label">Email:</label>
                                {{ form.email }}
                            </div>
                            <div class="mb-3">
                                <label for="id_address" class="form-label">Address:</label>
                                {{ form.address }}
                            </div>
                            <div class="mb-3">
                                <label for="id_organization" class="form-label">Organization:</label>
                                {{ form.organization }}
                            </div>
                            <button type="submit" class="btn btn-dark justify-content-center">Update Profile</button>
                        </form>
                        <div id="update-profile-message" class="mt-3" style="display: none;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('update-profile-form').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent the form from submitting normally
    
            const formData = new FormData(this);
    
            fetch("{% url 'update_profile' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': "{{ csrf_token }}",
                },
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    document.getElementById('update-profile-message').innerText = "Profile updated successfully!";
                    document.getElementById('update-profile-message').style.display = 'block';
                    document.getElementById('update-profile-form').reset(); // Optional: Reset the form
                    window.parent.postMessage('profileUpdated', '*');
                    // You can hide the iframe here if needed
                    // Hide the iframe
                } else {
                    document.getElementById('update-profile-message').innerText = "Failed to update profile.";
                    document.getElementById('update-profile-message').style.display = 'block';
                }
            })
            .catch(error => console.error('Error:', error));
        });
    </script>
</body>
</html>